nginx:
  image: jwilder/nginx-proxy
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  ports:
    - "80:80"
primeserver:
  build: .
  environment:
    #- VIRTUAL_HOST="~^sampleserver\..*\.xip\.io"
    - VIRTUAL_HOST=sampleserver.192.168.99.100.xip.io
    - VIRTUAL_PORT=9090
  ports:
    - 9090
  expose:
    - 9090
