consul:
  image: gliderlabs/consul-server:latest
  command: -server -bootstrap
  ports:
    - "8600:8600/udp"
    - "8500:8500"
    - "8400:8400"
    - "8300:8300"
    - "8301:8301"
    - "8302:8302"

haproxy:
  image: jakubsacha/haproxy-consul
  volumes:
    - "./haproxy:/home:rw"
  environment:
    CONSUL_CONNECT: consul:8500
    HAPROXY_DOMAIN: docker-workshops.trv
  dns:
    - "consul"
  links:
    - "consul:consul"
  ports:
    - "80:80"
    - "1936:1936"
