consul:
  image: gliderlabs/consul-server:latest
  command: -server -bootstrap -domain docker-workshops.trv -recursor 8.8.8.8
  ports:
    - "8600:8600/udp"
    - "53:8600/udp"
    - "8500:8500"
    - "8400:8400"
    - "8300:8300"
    - "8301:8301"
    - "8302:8302"

haproxy:
  image: jakubsacha/haproxy-consul
  volumes:
    - "./haproxy:/home:rw"
  environment:
    CONSUL_CONNECT: consul:8500
    HAPROXY_DOMAIN: docker-workshops.trv
  dns:
    - "consul"
  links:
    - "consul:consul"
  ports:
    - "80:80"
    - "1936:1936"


# metrics
influxdb:
  image: tutum/influxdb:latest
  ports:
    - 2003:2003
    - 8083:8083
    - 8086:8086
  environment:
    - ADMIN_USER=admin
    - INFLUXDB_INIT_PWD=admin
    - PRE_CREATE_DB=metrics
    - GRAPHITE_PROTOCOL=tcp
    - GRAPHITE_DB=metrics
    # TODO:
    #- GRAPHITE_template="tag1.tag2.tag3.measurement*"
    # servers.localhost.cpu.loadavg.10 -> .host.resource.measurement*
grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
  links:
    - influxdb
