influxdb:
  image: tutum/influxdb:latest
  ports:
    - 2003:2003
    - 8083:8083
    - 8086:8086
  environment:
    - ADMIN_USER=admin
    - INFLUXDB_INIT_PWD=admin
    - PRE_CREATE_DB=metrics
    - GRAPHITE_PROTOCOL=tcp
    - GRAPHITE_DB=metrics
    # TODO:
    #- GRAPHITE_template="tag1.tag2.tag3.measurement*"
    # servers.localhost.cpu.loadavg.10 -> .host.resource.measurement*
grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
  links:
    - influxdb
